### ISSUE TITLE
Broken in  WebStorm 2021.2 

### ISSUE THREAD

**Issue by psi-4ward** [hhariri/path-title#2]
```
2021-07-27 15:49:05,185 [   2968]  ERROR - llij.ide.plugins.PluginManager - com.intellij.diagnostic.PluginException: Fatal error initializing 'com.hadihariri.pathtitle.TitleComponent' [Plugin: com.hadihariri.pathtitle] 
java.util.concurrent.CompletionException: com.intellij.diagnostic.PluginException: Fatal error initializing 'com.hadihariri.pathtitle.TitleComponent' [Plugin: com.hadihariri.pathtitle]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
        at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
        at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
        at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
        at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:408)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.intellij.diagnostic.PluginException: Fatal error initializing 'com.hadihariri.pathtitle.TitleComponent' [Plugin: com.hadihariri.pathtitle]
        at com.intellij.serviceContainer.ComponentManagerImpl.handleInitComponentError$intellij_platform_serviceContainer(ComponentManagerImpl.kt:515)
        at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:60)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
        at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:407)
        at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:366)
        at com.intellij.idea.ApplicationLoader$startApp$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:136)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        ... 23 more
Caused by: java.lang.UnsupportedOperationException
        at com.intellij.serviceContainer.ComponentManagerImpl.registerComponentImplementation(ComponentManagerImpl.kt:1310)
        at com.hadihariri.pathtitle.TitleComponent.initComponent(TitleComponent.kt:12)
        at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
        ... 30 more
2021-07-27 15:49:05,196 [   2979]  ERROR - llij.ide.plugins.PluginManager - WebStorm 2021.2  Build #WS-212.4746.80 
2021-07-27 15:49:05,198 [   2981]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-07-27 15:49:05,198 [   2981]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2021-07-27 15:49:05,198 [   2981]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Path Title version: 0.1
```

Do you have an idea?

Greets

**Comment by allanlaal** [comment]
same issue in IDEA Ultimate 2021.2.1

**Comment by rossbu** [comment]
same in 2022.3. I would prefer to fork, or create a new one to continue this project if the owner is too busy these days. anyone?
